import os, time
import renderer as renderer_module

class FileRenderer(object):
    """
    Writes the result of the wrapped renderer to a file.
    Currently supports only text output.

    [ Properties ]

    path:
        The absolute or relative path to the file to create.

    suffix: (optional)
        If present, specifies that the filename is generated by the
        path, a generated unique id and the provided suffix. Useful
        for generating temporary files.
    """

    renderer = None
    path = None
    suffix = None

    def render(self, data={}, context={}):
        assert renderer_module.is_renderer(renderer), "'file.renderer' must be set to a renderer"
        assert path is not None, "'file.path' must be set"

        [ mime, content ] = self.renderer.render(data, context)

        if self.suffix:
            filename=self.path+"-"+str(os.getpid())+"-"+ \
            str(int(( time.time() % 1000 ) * 10000))+"." + self.suffix
        else:
            filename=self.path

        f = open(filename, "w")
        try:
            f.write(content)
        finally:
            f.close()

        return "Wrote result to "+filename
