CREATE TABLE METEO
( TIMESTAMP_UTC Timestamp NOT NULL,
  TIMESTAMP_LOCAL Timestamp NOT NULL,
  TEMP Numeric(3,1),
  HUM Numeric(3,1),
  WIND Numeric(4,1),
  WIND_DIR Smallint,
  WIND_GUST Numeric(4,1),
  WIND_GUST_DIR Smallint,
  DEW_POINT Numeric(3,1),
  RAIN Numeric(4,1),
  RAIN_RATE Numeric(4,1),
  PRESSURE Numeric(5,1),
  UV_INDEX Smallint,
  PRIMARY KEY (TIMESTAMP_UTC),
  KEY METEO_IDX (TIMESTAMP_LOCAL));
